In [1]:
import torch
import kornia as k
from sklearn.preprocessing import OneHotEncoder

In [15]:
labels = torch.tensor([8, 7, 2, 4, 7, 6, 1, 1, 6, 5, 1, 2, 2, 6, 7, 8, 0, 4, 8, 8, 7, 2, 2, 0,
        5, 8, 8, 9, 9, 1, 1, 4, 3, 5, 4, 6, 7, 6, 8, 5, 4, 6, 3, 4, 2, 9, 5, 6,
        7, 7, 2, 9, 9, 5, 8, 5, 7, 5, 6, 1, 0, 6, 3, 9, 4, 5, 9, 9, 1, 3, 0, 6,
        2, 3, 0, 9, 6, 3, 7, 1, 0, 4, 2, 4, 4, 0, 4, 2, 2, 3, 2, 6, 4, 4, 6, 4,
        2, 3, 1, 2])
classes = torch.unique(labels);classes,len(labels),len(classes)

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), 100, 10)

# 1. Single Label 

### 1.1. Manually

In [16]:
o = torch.zeros(len(labels),10)
for i,j in enumerate(labels):
    o[i,j] +=1
o[:5]

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.]])

### 1.2. Using kornia

In [17]:
k_one_hot = k.utils.one_hot(labels,num_classes=10,device='cpu')
k_one_hot.int()[:5]

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 1, 0, 0]], dtype=torch.int32)

## 1.3. Using Sklearn
* Must reshape the tensor to (-1,1)

In [18]:
enc = OneHotEncoder()

In [20]:
enc.fit(labels.reshape(-1,1))

OneHotEncoder(categories='auto', drop=None, dtype=<class 'numpy.float64'>,
              handle_unknown='error', sparse=True)

In [24]:
enc.transform(labels.reshape(-1,1)).toarray()[:5]

array([[0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.]])

# 2. Multi-labled data

In [26]:
import numpy as np

In [40]:
labels = np.array([['Blue','Round'],['Red','Square'],['Green','Triangle']])

## 2.1. Manually

In [30]:
classes = ['Blue','Red','Green','Round','Square','Triangle']
len(classes)

6

In [38]:
class_to_idx = {classes[i]:i for i in range(0,6)};class_to_idx

{'Blue': 0, 'Red': 1, 'Green': 2, 'Round': 3, 'Square': 4, 'Triangle': 5}

In [41]:
targets = torch.zeros(len(labels),len(classes))

In [45]:
for idx,sample in enumerate(labels):
    for tag in sample:
        targets[idx,class_to_idx[tag]] +=1

In [46]:
targets

tensor([[1., 0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 1., 0.],
        [0., 0., 1., 0., 0., 1.]])

## 2.2. Using Sklearn

In [49]:
multi = OneHotEncoder()

In [52]:
multi.fit_transform(labels).toarray()

array([[1., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1.]])

In [ ]:
torch.tensor(