In [38]:
import torch
import torchvision as tv
from sklearn.model_selection import train_test_split
from glob import glob
import os

## Steps to create training and validation sets 

This is very similar to ImageFolder dataset in torchvision. A generic data loader where the images are arranged in this way:

    root/dog/xxx.png
    root/dog/xxy.png
    root/dog/xxz.png

    root/cat/123.png
    root/cat/nsdf3.png
    root/cat/asd932_.png

Steps are:
1. Create a set of images' pathnames and save them in x 
2. Extracte directories' names and save them in 'c'
3. Keys are the unique values in 'c'
4. Generate values as a sequence of numbers from 0 to 50
5. Define class_to_idx by joining keys and values
6. Create a list with pathes and direcotry names
7. Map class values to directory name in y


In [97]:
path = ('/Users/aymanjabri/notebooks/Artwork/data/images/images')

x = glob(path+'/**/*') # contains path to all files

#extract directory names and save them into a list
c = [os.path.basename(os.path.dirname(i)) for i in x]

#create a dictionary list from directory names and a sequence values
keys = np.unique(c)
values = np.arange(0,50)
class_to_idx = dict(zip(keys,values))

In [96]:
d = [[os.path.basename(os.path.dirname(i)),os.path.abspath(i)] for i in x]
d[:5]

[['Piet_Mondrian',
  '/Users/aymanjabri/notebooks/Artwork/data/images/images/Piet_Mondrian/Piet_Mondrian_38.jpg'],
 ['Piet_Mondrian',
  '/Users/aymanjabri/notebooks/Artwork/data/images/images/Piet_Mondrian/Piet_Mondrian_10.jpg'],
 ['Piet_Mondrian',
  '/Users/aymanjabri/notebooks/Artwork/data/images/images/Piet_Mondrian/Piet_Mondrian_11.jpg'],
 ['Piet_Mondrian',
  '/Users/aymanjabri/notebooks/Artwork/data/images/images/Piet_Mondrian/Piet_Mondrian_39.jpg'],
 ['Piet_Mondrian',
  '/Users/aymanjabri/notebooks/Artwork/data/images/images/Piet_Mondrian/Piet_Mondrian_13.jpg']]

In [41]:
np.array(d).shape

(8446, 2)

In [42]:
y = [class_to_idx[d[i][0]] for i in range(len(d))]

In [72]:
len(y),max(y),min(y),np.bincount(y)

(8446,
 49,
 0,
 array([328, 259, 193,  99, 181,  91,  55,  73,  70, 128, 702,  90,  67,
         87,  31, 291, 120,  43, 119, 117,  59, 186,  70,  81, 137,  24,
         81, 102, 126, 143, 239,  49, 171, 439,  47, 311, 188, 141, 336,
         84, 134, 109, 262, 194, 139, 164, 255,  88, 877,  66]))

In [55]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [59]:
len(x_train),len(x_test)

(6756, 1690)

In [121]:
np.bincount(y_train),np.bincount(y_test)

(array([268, 204, 148,  83, 142,  66,  41,  64,  58,  99, 560,  75,  50,
         65,  24, 237,  94,  34,  91,  92,  48, 148,  53,  59, 110,  19,
         71,  81, 102, 109, 197,  41, 138, 356,  32, 263, 154, 115, 267,
         73, 112,  85, 224, 155, 106, 131, 205,  70, 686,  51]),
 array([ 60,  55,  45,  16,  39,  25,  14,   9,  12,  29, 142,  15,  17,
         22,   7,  54,  26,   9,  28,  25,  11,  38,  17,  22,  27,   5,
         10,  21,  24,  34,  42,   8,  33,  83,  15,  48,  34,  26,  69,
         11,  22,  24,  38,  39,  33,  33,  50,  18, 191,  15]))

# A new way to do this with torchvision 0.4.0 and above

In [2]:
#data = dataset created using either torchvision or any other custom dataset class
trainset,testset = torch.utils.data.random_split(data,[800,200])

# train_size = int(0.8 * len(full_dataset))
# test_size = len(full_dataset) - train_size

# train_dataset, test_dataset = torch.utils.data.random_split(full_dataset, [train_size, test_size])

NameError: name 'torch' is not defined